[package]
name = "crafting_interpreters"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
float_eq = "0.7.0"
peekmore = "1.0.0"
rustyline = "9.1.2"
thiserror = "1.0.31"
